### ISSUE TITLE
Option for multiline strings

### ISSUE THREAD

**Issue by rienafairefr** [jrhouston/tfk8s#13]
Not really a bug, more like a feature request

Some manifests contain multiline strings, like json/yaml embedded files in a configmap or whatever. When outputting from the cluster `-o yaml`, the multiline values are (usually, this might depend on their creator) using multiline yaml value, an example in a pgo-config configmap: 
```
  pgo-pg-sa.json: |-
    {
       "apiVersion":"v1",
       "kind":"ServiceAccount",
       "metadata":{
          "name":"pgo-pg",
          "namespace":"{{.TargetNamespace}}",
          "labels":{
             "vendor":"crunchydata"
          }
       }
    }
```
Importing that yaml into terraform through tfk8s,the manifests seem okay but all the multiline values are `"...\n...\n...\n"`
This is working fine AFAICS, but for editabitility of the generated .tf, that'd be nice to use the multiline facilities in hcl, like the heredocs:
```
"pgo-pg-sa.json"= <<JSON
    {
       "apiVersion":"v1",
       "kind":"ServiceAccount",
       "metadata":{
          "name":"pgo-pg",
          "namespace":"{{.TargetNamespace}}",
          "labels":{
             "vendor":"crunchydata"
          }
       }
    }
JSON
```

**Comment by jrhouston** [comment]
Thanks for opening this @rienafairefr – we are using Terraform's repl package to do the formatting to HCL and it looks they [recently added support for this](https://github.com/hashicorp/terraform/commit/4e7607deb5383a4be421d16513f22325dc2e55fa) so we should be able to bring this in.

I had a quick look and there's some additional munging we will have to do because the interface has changed to use `cty.Value` rather than `map[string]interface{}`.
