### ISSUE TITLE
Remove dependency on terraform/repl

### ISSUE THREAD

**Issue by jrhouston** [jrhouston/tfk8s#18]
https://github.com/hashicorp/terraform/commit/36d0a50427309875e9f7e8084936072db055e124 made repl internal for Terraform 1.0 so we'll need to duplicate the [FormatValue](https://github.com/hashicorp/terraform/blob/main/internal/repl/format.go) function in this repo.

**Comment by penguincoder** [comment]
I am also having an issue building `tfk8s` on my workstation (Fedora 34) due to Terraform. It appears that Terraform depends on [tencentcloud-sdk-go](https://github.com/TencentCloud/tencentcloud-sdk-go) which has recently gone through a serious change in their versioning. All of the old tags were removed and then the versioning on the module reset from 3 back to version 1. I have not used `go` enough to figure out how to tell it that commit [f8fa457a3c7246de0b141f2e68bef19f17180130](https://github.com/TencentCloud/tencentcloud-sdk-go/tree/f8fa457a3c7246de0b141f2e68bef19f17180130) is the version it needs to satisfy the dependency.

```bash
[user@host ~]$ go install github.com/jrhouston/tfk8s@latest
go install github.com/jrhouston/tfk8s@latest: github.com/jrhouston/tfk8s@none updating to
	github.com/jrhouston/tfk8s@v0.1.3 requires
	github.com/hashicorp/terraform@v0.14.8 requires
	github.com/tencentcloud/tencentcloud-sdk-go@v3.0.82+incompatible: reading github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.82: unknown revision v3.0.82
```

For some reason, though, I was able to successfully build `tfk8s` in Docker (with a minor change, PR is coming!)

**Comment by rymnc** [comment]
@penguincoder, I too have the same issue on my Fedora 34 workstation. Can you share the details of how you built it in docker?

**Comment by penguincoder** [comment]
it built much like any other docker container:

```
$ docker build -t tfk8s .
Sending build context to Docker daemon  277.5kB
Step 1/10 : FROM golang:1.16-alpine as build
 ---> a84d737792c2
Step 2/10 : WORKDIR /build
 ---> Using cache
 ---> 8ede4f31c261
Step 3/10 : COPY go.* ./
 ---> Using cache
 ---> 803956f8ee64
Step 4/10 : RUN go mod download
 ---> Using cache
 ---> 31f6a6847212
Step 5/10 : COPY . .
 ---> Using cache
 ---> a842302afecc
Step 6/10 : RUN apk --no-cache add make
 ---> Using cache
 ---> e326b1eb3ee4
Step 7/10 : RUN CGO_ENABLED=0 make build
 ---> Using cache
 ---> dbd92e71d75e
Step 8/10 : FROM scratch
 ---> 
Step 9/10 : COPY --from=build /build/tfk8s /bin/tfk8s
 ---> Using cache
 ---> 23f741ab4a96
Step 10/10 : ENTRYPOINT ["/bin/tfk8s"]
 ---> Using cache
 ---> 0cd3eae024bd
Successfully built 0cd3eae024bd
Successfully tagged tfk8s:latest
```

**Comment by rymnc** [comment]
Ah, thanks. I did manage to figure it out. I copied the binary to my local machine so I don't have to use docker everytime with this.
By the way, are you using this in production (with kubernetes-alpha)?

**Comment by penguincoder** [comment]
That's exactly what I did, too. Once I got the binary onto my local machine I was able to convert all of my descriptors easily.

In the end, I switched to the Helm provider because (I think) the kubernetes-alpha provider needs a specific set of configuration options that I could not combine with the correct number of chickens to get it to work. I seem to remember thinking that it really wants a `kubeconfig` file, but due to security restrictions in my GKE cluster I can't provide that. YMMV

**Comment by rymnc** [comment]
Yeah, I've had the same issue with Kubernetes-alpha. I'll look into the helm provider, thanks!

**Comment by jrhouston** [comment]
@penguincoder @rymnc I'm also a maintainer on the kubernetes-alpha project so if you ran into problems configuring it please an open an issue there so we can try to reproduce and fix it. 

Haven't had time to remove this repl dependency yet – will try and get to it soon.
